//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse HelloWorld(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/F2C", ReplyAction="*")]
        double F2C(double F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/F2C", ReplyAction="*")]
        System.Threading.Tasks.Task<double> F2CAsync(double F);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/C2F", ReplyAction="*")]
        double C2F(double C);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/C2F", ReplyAction="*")]
        System.Threading.Tasks.Task<double> C2FAsync(double C);
        
        // CODEGEN: Generating message contract since element name ListAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll", ReplyAction="*")]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse ListAll(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse> ListAllAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest request);
        
        // CODEGEN: Generating message contract since element name DateTimeDisplayResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateTimeDisplay", ReplyAction="*")]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse DateTimeDisplay(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateTimeDisplay", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse> DateTimeDisplayAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EuroToLei", ReplyAction="*")]
        double EuroToLei(double E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EuroToLei", ReplyAction="*")]
        System.Threading.Tasks.Task<double> EuroToLeiAsync(double E);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeiToEuro", ReplyAction="*")]
        double LeiToEuro(double L);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LeiToEuro", ReplyAction="*")]
        System.Threading.Tasks.Task<double> LeiToEuroAsync(double L);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAll", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequestBody Body;
        
        public ListAllRequest() {
        }
        
        public ListAllRequest(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAllRequestBody {
        
        public ListAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponseBody Body;
        
        public ListAllResponse() {
        }
        
        public ListAllResponse(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ArrayOfString ListAllResult;
        
        public ListAllResponseBody() {
        }
        
        public ListAllResponseBody(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ArrayOfString ListAllResult) {
            this.ListAllResult = ListAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateTimeDisplayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateTimeDisplay", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequestBody Body;
        
        public DateTimeDisplayRequest() {
        }
        
        public DateTimeDisplayRequest(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DateTimeDisplayRequestBody {
        
        public DateTimeDisplayRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateTimeDisplayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateTimeDisplayResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponseBody Body;
        
        public DateTimeDisplayResponse() {
        }
        
        public DateTimeDisplayResponse(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateTimeDisplayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DateTimeDisplayResult;
        
        public DateTimeDisplayResponseBody() {
        }
        
        public DateTimeDisplayResponseBody(string DateTimeDisplayResult) {
            this.DateTimeDisplayResult = DateTimeDisplayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap>, ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.HelloWorld(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequestBody();
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse retVal = ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse> ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.HelloWorldAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.HelloWorldRequestBody();
            return ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public double F2C(double F) {
            return base.Channel.F2C(F);
        }
        
        public System.Threading.Tasks.Task<double> F2CAsync(double F) {
            return base.Channel.F2CAsync(F);
        }
        
        public double C2F(double C) {
            return base.Channel.C2F(C);
        }
        
        public System.Threading.Tasks.Task<double> C2FAsync(double C) {
            return base.Channel.C2FAsync(C);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.ListAll(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest request) {
            return base.Channel.ListAll(request);
        }
        
        public ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ArrayOfString ListAll() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequestBody();
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse retVal = ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).ListAll(inValue);
            return retVal.Body.ListAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse> ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.ListAllAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest request) {
            return base.Channel.ListAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllResponse> ListAllAsync() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.ListAllRequestBody();
            return ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).ListAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.DateTimeDisplay(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest request) {
            return base.Channel.DateTimeDisplay(request);
        }
        
        public string DateTimeDisplay() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequestBody();
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse retVal = ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).DateTimeDisplay(inValue);
            return retVal.Body.DateTimeDisplayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse> ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap.DateTimeDisplayAsync(ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest request) {
            return base.Channel.DateTimeDisplayAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayResponse> DateTimeDisplayAsync() {
            ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest inValue = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequest();
            inValue.Body = new ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.DateTimeDisplayRequestBody();
            return ((ClientuAlaBlanaCuFormDianalaDinCareTrebe.ServiceReference1.WebService1Soap)(this)).DateTimeDisplayAsync(inValue);
        }
        
        public double EuroToLei(double E) {
            return base.Channel.EuroToLei(E);
        }
        
        public System.Threading.Tasks.Task<double> EuroToLeiAsync(double E) {
            return base.Channel.EuroToLeiAsync(E);
        }
        
        public double LeiToEuro(double L) {
            return base.Channel.LeiToEuro(L);
        }
        
        public System.Threading.Tasks.Task<double> LeiToEuroAsync(double L) {
            return base.Channel.LeiToEuroAsync(L);
        }
    }
}
