//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name getAllNamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllNames", ReplyAction="*")]
        HWClient.ServiceReference1.getAllNamesResponse getAllNames(HWClient.ServiceReference1.getAllNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllNames", ReplyAction="*")]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllNamesResponse> getAllNamesAsync(HWClient.ServiceReference1.getAllNamesRequest request);
        
        // CODEGEN: Generating message contract since element name getAllPricesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllPrices", ReplyAction="*")]
        HWClient.ServiceReference1.getAllPricesResponse getAllPrices(HWClient.ServiceReference1.getAllPricesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllPrices", ReplyAction="*")]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllPricesResponse> getAllPricesAsync(HWClient.ServiceReference1.getAllPricesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addItem", ReplyAction="*")]
        HWClient.ServiceReference1.addItemResponse addItem(HWClient.ServiceReference1.addItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addItem", ReplyAction="*")]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.addItemResponse> addItemAsync(HWClient.ServiceReference1.addItemRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePrice", ReplyAction="*")]
        HWClient.ServiceReference1.updatePriceResponse updatePrice(HWClient.ServiceReference1.updatePriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updatePrice", ReplyAction="*")]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.updatePriceResponse> updatePriceAsync(HWClient.ServiceReference1.updatePriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllNames", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.getAllNamesRequestBody Body;
        
        public getAllNamesRequest() {
        }
        
        public getAllNamesRequest(HWClient.ServiceReference1.getAllNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllNamesRequestBody {
        
        public getAllNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.getAllNamesResponseBody Body;
        
        public getAllNamesResponse() {
        }
        
        public getAllNamesResponse(HWClient.ServiceReference1.getAllNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HWClient.ServiceReference1.ArrayOfString getAllNamesResult;
        
        public getAllNamesResponseBody() {
        }
        
        public getAllNamesResponseBody(HWClient.ServiceReference1.ArrayOfString getAllNamesResult) {
            this.getAllNamesResult = getAllNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllPricesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllPrices", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.getAllPricesRequestBody Body;
        
        public getAllPricesRequest() {
        }
        
        public getAllPricesRequest(HWClient.ServiceReference1.getAllPricesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllPricesRequestBody {
        
        public getAllPricesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllPricesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllPricesResponse", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.getAllPricesResponseBody Body;
        
        public getAllPricesResponse() {
        }
        
        public getAllPricesResponse(HWClient.ServiceReference1.getAllPricesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllPricesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public HWClient.ServiceReference1.ArrayOfString getAllPricesResult;
        
        public getAllPricesResponseBody() {
        }
        
        public getAllPricesResponseBody(HWClient.ServiceReference1.ArrayOfString getAllPricesResult) {
            this.getAllPricesResult = getAllPricesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addItem", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.addItemRequestBody Body;
        
        public addItemRequest() {
        }
        
        public addItemRequest(HWClient.ServiceReference1.addItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int price;
        
        public addItemRequestBody() {
        }
        
        public addItemRequestBody(string name, int price) {
            this.name = name;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.addItemResponseBody Body;
        
        public addItemResponse() {
        }
        
        public addItemResponse(HWClient.ServiceReference1.addItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addItemResponseBody {
        
        public addItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePrice", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.updatePriceRequestBody Body;
        
        public updatePriceRequest() {
        }
        
        public updatePriceRequest(HWClient.ServiceReference1.updatePriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updatePriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int price;
        
        public updatePriceRequestBody() {
        }
        
        public updatePriceRequestBody(string name, int price) {
            this.name = name;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updatePriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updatePriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public HWClient.ServiceReference1.updatePriceResponseBody Body;
        
        public updatePriceResponse() {
        }
        
        public updatePriceResponse(HWClient.ServiceReference1.updatePriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updatePriceResponseBody {
        
        public updatePriceResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HWClient.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HWClient.ServiceReference1.WebService1Soap>, HWClient.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HWClient.ServiceReference1.getAllNamesResponse HWClient.ServiceReference1.WebService1Soap.getAllNames(HWClient.ServiceReference1.getAllNamesRequest request) {
            return base.Channel.getAllNames(request);
        }
        
        public HWClient.ServiceReference1.ArrayOfString getAllNames() {
            HWClient.ServiceReference1.getAllNamesRequest inValue = new HWClient.ServiceReference1.getAllNamesRequest();
            inValue.Body = new HWClient.ServiceReference1.getAllNamesRequestBody();
            HWClient.ServiceReference1.getAllNamesResponse retVal = ((HWClient.ServiceReference1.WebService1Soap)(this)).getAllNames(inValue);
            return retVal.Body.getAllNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllNamesResponse> HWClient.ServiceReference1.WebService1Soap.getAllNamesAsync(HWClient.ServiceReference1.getAllNamesRequest request) {
            return base.Channel.getAllNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllNamesResponse> getAllNamesAsync() {
            HWClient.ServiceReference1.getAllNamesRequest inValue = new HWClient.ServiceReference1.getAllNamesRequest();
            inValue.Body = new HWClient.ServiceReference1.getAllNamesRequestBody();
            return ((HWClient.ServiceReference1.WebService1Soap)(this)).getAllNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HWClient.ServiceReference1.getAllPricesResponse HWClient.ServiceReference1.WebService1Soap.getAllPrices(HWClient.ServiceReference1.getAllPricesRequest request) {
            return base.Channel.getAllPrices(request);
        }
        
        public HWClient.ServiceReference1.ArrayOfString getAllPrices() {
            HWClient.ServiceReference1.getAllPricesRequest inValue = new HWClient.ServiceReference1.getAllPricesRequest();
            inValue.Body = new HWClient.ServiceReference1.getAllPricesRequestBody();
            HWClient.ServiceReference1.getAllPricesResponse retVal = ((HWClient.ServiceReference1.WebService1Soap)(this)).getAllPrices(inValue);
            return retVal.Body.getAllPricesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllPricesResponse> HWClient.ServiceReference1.WebService1Soap.getAllPricesAsync(HWClient.ServiceReference1.getAllPricesRequest request) {
            return base.Channel.getAllPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<HWClient.ServiceReference1.getAllPricesResponse> getAllPricesAsync() {
            HWClient.ServiceReference1.getAllPricesRequest inValue = new HWClient.ServiceReference1.getAllPricesRequest();
            inValue.Body = new HWClient.ServiceReference1.getAllPricesRequestBody();
            return ((HWClient.ServiceReference1.WebService1Soap)(this)).getAllPricesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HWClient.ServiceReference1.addItemResponse HWClient.ServiceReference1.WebService1Soap.addItem(HWClient.ServiceReference1.addItemRequest request) {
            return base.Channel.addItem(request);
        }
        
        public void addItem(string name, int price) {
            HWClient.ServiceReference1.addItemRequest inValue = new HWClient.ServiceReference1.addItemRequest();
            inValue.Body = new HWClient.ServiceReference1.addItemRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            HWClient.ServiceReference1.addItemResponse retVal = ((HWClient.ServiceReference1.WebService1Soap)(this)).addItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.addItemResponse> HWClient.ServiceReference1.WebService1Soap.addItemAsync(HWClient.ServiceReference1.addItemRequest request) {
            return base.Channel.addItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<HWClient.ServiceReference1.addItemResponse> addItemAsync(string name, int price) {
            HWClient.ServiceReference1.addItemRequest inValue = new HWClient.ServiceReference1.addItemRequest();
            inValue.Body = new HWClient.ServiceReference1.addItemRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            return ((HWClient.ServiceReference1.WebService1Soap)(this)).addItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HWClient.ServiceReference1.updatePriceResponse HWClient.ServiceReference1.WebService1Soap.updatePrice(HWClient.ServiceReference1.updatePriceRequest request) {
            return base.Channel.updatePrice(request);
        }
        
        public void updatePrice(string name, int price) {
            HWClient.ServiceReference1.updatePriceRequest inValue = new HWClient.ServiceReference1.updatePriceRequest();
            inValue.Body = new HWClient.ServiceReference1.updatePriceRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            HWClient.ServiceReference1.updatePriceResponse retVal = ((HWClient.ServiceReference1.WebService1Soap)(this)).updatePrice(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HWClient.ServiceReference1.updatePriceResponse> HWClient.ServiceReference1.WebService1Soap.updatePriceAsync(HWClient.ServiceReference1.updatePriceRequest request) {
            return base.Channel.updatePriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<HWClient.ServiceReference1.updatePriceResponse> updatePriceAsync(string name, int price) {
            HWClient.ServiceReference1.updatePriceRequest inValue = new HWClient.ServiceReference1.updatePriceRequest();
            inValue.Body = new HWClient.ServiceReference1.updatePriceRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            return ((HWClient.ServiceReference1.WebService1Soap)(this)).updatePriceAsync(inValue);
        }
    }
}
